package view;

public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        Area_trabalho = new javax.swing.JPanel();
        jmbMenuPrincipal = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        Cadastro_Funcionario = new javax.swing.JMenuItem();
        Cadastro_veiculo = new javax.swing.JMenuItem();
        Controle_Entrada_Saida = new javax.swing.JMenu();
        Nova_Entrada_Saida = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmOutros = new javax.swing.JMenu();
        Sobre = new javax.swing.JMenuItem();
        jmiLogout = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Area_trabalho.setBackground(new java.awt.Color(50, 50, 50));
        Area_trabalho.setPreferredSize(new java.awt.Dimension(809, 606));

        javax.swing.GroupLayout Area_trabalhoLayout = new javax.swing.GroupLayout(Area_trabalho);
        Area_trabalho.setLayout(Area_trabalhoLayout);
        Area_trabalhoLayout.setHorizontalGroup(
            Area_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        Area_trabalhoLayout.setVerticalGroup(
            Area_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        Cadastro.setText("Cadastros");

        Cadastro_Funcionario.setText("Cadastro Funcionario");
        Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_FuncionarioActionPerformed(evt);
            }
        });
        Cadastro.add(Cadastro_Funcionario);

        Cadastro_veiculo.setText("Cadastro Veiculo");
        Cadastro_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_veiculoActionPerformed(evt);
            }
        });
        Cadastro.add(Cadastro_veiculo);

        jmbMenuPrincipal.add(Cadastro);

        Controle_Entrada_Saida.setText("Movimentações de Veículos");

        Nova_Entrada_Saida.setText("Controle de Entradas/Saídas");
        Nova_Entrada_Saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nova_Entrada_SaidaActionPerformed(evt);
            }
        });
        Controle_Entrada_Saida.add(Nova_Entrada_Saida);

        jmbMenuPrincipal.add(Controle_Entrada_Saida);

        jMenu3.setText("Controle de Gastos");
        jmbMenuPrincipal.add(jMenu3);

        jmOutros.setText("Outros");

        Sobre.setText("Sobre");
        Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreActionPerformed(evt);
            }
        });
        jmOutros.add(Sobre);

        jmiLogout.setText("Logout");
        jmiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoutActionPerformed(evt);
            }
        });
        jmOutros.add(jmiLogout);

        jmbMenuPrincipal.add(jmOutros);

        setJMenuBar(jmbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Area_trabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Area_trabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_FuncionarioActionPerformed
        FuncionarioView cadastro = new FuncionarioView();
        Area_trabalho.add(cadastro);
        cadastro.setVisible(true);   
    }//GEN-LAST:event_Cadastro_FuncionarioActionPerformed

    private void Cadastro_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_veiculoActionPerformed
        VeiculoView veiculo = new VeiculoView();
        Area_trabalho.add(veiculo);
        veiculo.setVisible(true);
    }//GEN-LAST:event_Cadastro_veiculoActionPerformed

    private void Nova_Entrada_SaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nova_Entrada_SaidaActionPerformed
        MovimentacaoView entrada = new MovimentacaoView();
        Area_trabalho.add(entrada);
        entrada.setVisible(true);
    }//GEN-LAST:event_Nova_Entrada_SaidaActionPerformed

    private void jmiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoutActionPerformed
        setVisible(false);
        LoginView login = new LoginView();
        login.setVisible(true);
    }//GEN-LAST:event_jmiLogoutActionPerformed

    private void SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SobreActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Area_trabalho;
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem Cadastro_Funcionario;
    private javax.swing.JMenuItem Cadastro_veiculo;
    private javax.swing.JMenu Controle_Entrada_Saida;
    private javax.swing.JMenuItem Nova_Entrada_Saida;
    private javax.swing.JMenuItem Sobre;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jmOutros;
    private javax.swing.JMenuBar jmbMenuPrincipal;
    private javax.swing.JMenuItem jmiLogout;
    // End of variables declaration//GEN-END:variables
}
