/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author luixc
 */
public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        Area_trabalho = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        Cadastro_Funcionario = new javax.swing.JMenuItem();
        Cadastro_veiculo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Controle_Entrada_Saida = new javax.swing.JMenu();
        Nova_Entrada_Saida = new javax.swing.JMenuItem();
        Visualizar_Entrada_Saida = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        SOBRE = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Area_trabalho.setBackground(new java.awt.Color(50, 50, 50));
        Area_trabalho.setPreferredSize(new java.awt.Dimension(809, 606));

        javax.swing.GroupLayout Area_trabalhoLayout = new javax.swing.GroupLayout(Area_trabalho);
        Area_trabalho.setLayout(Area_trabalhoLayout);
        Area_trabalhoLayout.setHorizontalGroup(
            Area_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );
        Area_trabalhoLayout.setVerticalGroup(
            Area_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        Cadastro.setText("CADASTRO");

        Cadastro_Funcionario.setText("Cadastro Funcionario");
        Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_FuncionarioActionPerformed(evt);
            }
        });
        Cadastro.add(Cadastro_Funcionario);

        Cadastro_veiculo.setText("Cadastro Veiculo");
        Cadastro_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_veiculoActionPerformed(evt);
            }
        });
        Cadastro.add(Cadastro_veiculo);

        jMenuItem1.setText("Trocar Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Cadastro.add(jMenuItem1);

        jMenuBar1.add(Cadastro);

        Controle_Entrada_Saida.setText("CONTROLE ENTRADA/SAIDA ");

        Nova_Entrada_Saida.setText("Nova Entrada/Saida");
        Nova_Entrada_Saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nova_Entrada_SaidaActionPerformed(evt);
            }
        });
        Controle_Entrada_Saida.add(Nova_Entrada_Saida);

        Visualizar_Entrada_Saida.setText("Visualizar Entrada/Saida");
        Visualizar_Entrada_Saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Visualizar_Entrada_SaidaActionPerformed(evt);
            }
        });
        Controle_Entrada_Saida.add(Visualizar_Entrada_Saida);

        jMenuBar1.add(Controle_Entrada_Saida);

        jMenu3.setText("CONTROLE DE GASTOS");
        jMenuBar1.add(jMenu3);

        SOBRE.setText("Sobre");
        jMenuBar1.add(SOBRE);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Area_trabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Area_trabalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_FuncionarioActionPerformed
        FuncionarioView cadastro = new FuncionarioView();
        Area_trabalho.add(cadastro);
        cadastro.setVisible(true);   
    }//GEN-LAST:event_Cadastro_FuncionarioActionPerformed

    private void Cadastro_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_veiculoActionPerformed
        VeiculoView veiculo = new VeiculoView();
        Area_trabalho.add(veiculo);
        veiculo.setVisible(true);
    }//GEN-LAST:event_Cadastro_veiculoActionPerformed

    private void Nova_Entrada_SaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nova_Entrada_SaidaActionPerformed
        EntradaeSaidaView entrada = new EntradaeSaidaView();
        Area_trabalho.add(entrada);
        entrada.setVisible(true);
    }//GEN-LAST:event_Nova_Entrada_SaidaActionPerformed

    private void Visualizar_Entrada_SaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Visualizar_Entrada_SaidaActionPerformed
        VisualizarEntradaeSaidaView visualizar = new  VisualizarEntradaeSaidaView();
        Area_trabalho.add(visualizar);
        visualizar.setVisible(true);
    }//GEN-LAST:event_Visualizar_Entrada_SaidaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setVisible(false);
        LoginView login = new LoginView();
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Area_trabalho;
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem Cadastro_Funcionario;
    private javax.swing.JMenuItem Cadastro_veiculo;
    private javax.swing.JMenu Controle_Entrada_Saida;
    private javax.swing.JMenuItem Nova_Entrada_Saida;
    private javax.swing.JMenu SOBRE;
    private javax.swing.JMenuItem Visualizar_Entrada_Saida;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
