package view;

import util.JOptionPaneCustom;
import controller.VeiculoController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.VeiculoModel;
import util.Pesquisa;

public class VeiculoView extends javax.swing.JInternalFrame {

    VeiculoController veiculoController = new VeiculoController();
    boolean tabelaAtiva = true;

    public VeiculoView() {
        initComponents();
        resetTela();
        jtfID.setEditable(false);
        carregarTabela();
    }

    private void limparCampos() {
        jtfID.setText("");
        jtfPlaca.setText("");
        jtfMarca.setText("");
        jtfModelo.setText("");
        jftfAno.setText("");
    }

    public void carregarTabela() {

        ArrayList<VeiculoModel> veiculos = veiculoController.selecionarTodos();
        DefaultTableModel modelo = (DefaultTableModel) TabelaVeiculos.getModel();
        modelo.setRowCount(0);

        for (int i = 0; i < veiculos.size(); i++) {
            modelo.addRow(new String[]{
                String.valueOf(veiculos.get(i).getId()),
                veiculos.get(i).getPlaca(),
                veiculos.get(i).getMarca(),
                veiculos.get(i).getModelo(),
                String.valueOf(veiculos.get(i).getAno()),
                veiculos.get(i).getStatus()
            });
        }
    }

    public void resetTela() {
        //Ativa os botões Novo, Limpar e Pesquisar
        jbNovo.setEnabled(true);
        jbLimpar.setEnabled(true);
        jbPesquisar.setEnabled(true);

        //Desativa os outros botões e campos de texto
        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbCancelar.setEnabled(false);

        jtfPlaca.setEditable(false);
        jtfMarca.setEditable(false);
        jtfModelo.setEditable(false);
        jftfAno.setEditable(false);

        //Recarrega a tabela, limpa os campos e ativa a flag do evento de clique da tabela
        carregarTabela();
        limparCampos();
        tabelaAtiva = true;
    }

    public void ativarEdicao() {
        //Desabilita os botões Novo, Editar, Excluir e Limpar
        jbNovo.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbLimpar.setEnabled(false);

        //Habilita o botão Salvar e Cancelar e os campos de texto
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jtfPlaca.setEditable(true);
        jtfMarca.setEditable(true);
        jtfModelo.setEditable(true);
        jftfAno.setEditable(true);

        //Desativa a flag do evento de clique da tabela
        tabelaAtiva = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jlMarca = new javax.swing.JLabel();
        jlAno = new javax.swing.JLabel();
        jlPlaca = new javax.swing.JLabel();
        jftfAno = new javax.swing.JFormattedTextField();
        jtfMarca = new javax.swing.JTextField();
        jlModelo = new javax.swing.JLabel();
        jtfModelo = new javax.swing.JTextField();
        jlID = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jbLimpar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        jtfPlaca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaVeiculos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Cadastro de Veículos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jbNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 80, -1));

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jbExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 45, 80, -1));

        jlMarca.setText("Marca:");
        getContentPane().add(jlMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 262, -1, -1));

        jlAno.setText("Ano:");
        getContentPane().add(jlAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 376, -1, -1));

        jlPlaca.setText("Placa:");
        getContentPane().add(jlPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 207, -1, -1));

        jftfAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(jftfAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 396, 180, 25));

        jtfMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jtfMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 282, 180, 25));

        jlModelo.setText("Modelo:");
        getContentPane().add(jlModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 319, -1, -1));
        getContentPane().add(jtfModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 339, 180, 25));

        jlID.setText("ID:");
        getContentPane().add(jlID, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 150, -1, -1));
        getContentPane().add(jtfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 170, 180, 25));

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 10, 80, -1));

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 80, 80, -1));

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jbPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 115, -1, -1));
        getContentPane().add(jtfPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 229, 180, -1));

        TabelaVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Placa", "Marca", "Modelo", "Ano", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaVeiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaVeiculos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 580, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        limparCampos();
        ativarEdicao();
        jbLimpar.setEnabled(true);
        jbPesquisar.setEnabled(false);


    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        VeiculoModel veiculo = new VeiculoModel();
        String placa = jtfPlaca.getText();
        String Marca = jtfMarca.getText();
        String modelo = jtfModelo.getText();
        String Ano = jftfAno.getText();
        
        String formato1Regex = "[A-Z]{3}[0-9]{4}";
        String formato2Regex = "[A-Z]{3}[0-9]{1}[A-Z]{1}[0-9]{2}";

        if (placa.isEmpty() || Marca.isEmpty() || modelo.isEmpty() || Ano.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, prencha todos os campos solicitados.");
        } else if (placa.length() != 7) {
            JOptionPane.showMessageDialog(this, "A placa deve conter exatamente 7 caracteres.");
        } else if (!placa.matches(formato1Regex) && !placa.matches(formato2Regex)) {
            JOptionPane.showMessageDialog(this, "Placa de veículo inválida.");
        } else if ("".equals(jtfID.getText())) {
            veiculo.setPlaca(jtfPlaca.getText());
            veiculo.setMarca(jtfMarca.getText());
            veiculo.setModelo(jtfModelo.getText());
            veiculo.setAno(Integer.parseInt(jftfAno.getText()));

            if (veiculoController.inserir(veiculo)) {
                JOptionPane.showMessageDialog(this, "Veículo cadastrado com sucesso.");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar o veículo.");
            }
        } //Caso contrário, uma linha da tabela foi selecionada e o botão Editar foi pressionado
        else {
            veiculo.setId(Integer.parseInt(jtfID.getText()));
            veiculo.setPlaca(jtfPlaca.getText());
            veiculo.setMarca(jtfMarca.getText());
            veiculo.setModelo(jtfModelo.getText());
            veiculo.setAno(Integer.parseInt(jftfAno.getText()));
            if (veiculoController.editar(veiculo)) {
                JOptionPane.showMessageDialog(this, "Os dados do veículo foram atualizados com sucesso.");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar dados do veículo.");
            }
        }

        resetTela();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        ativarEdicao();
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed

        String placa = jtfPlaca.getText();
        String Marca = jtfMarca.getText();
        String modelo = jtfModelo.getText();
        String Ano = jftfAno.getText();

        if (placa.isEmpty() || Marca.isEmpty() || modelo.isEmpty() || Ano.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não a nada a ser excluido.");
        } else if (JOptionPane.showConfirmDialog(null, "Tem certeza de que deseja excluir esse Cadastro ?", "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Veiculo apagado com sucesso.");

            VeiculoModel veiculo = new VeiculoModel();
            veiculo.setId(Integer.parseInt(jtfID.getText()));
            veiculoController.excluir(veiculo);
            resetTela();
            limparCampos();
        } else if (JOptionPane.CLOSED_OPTION == JOptionPane.CLOSED_OPTION) {
            JOptionPane.showMessageDialog(this, "Operação cancelada.");
            limparCampos();
            resetTela();
        }
        carregarTabela();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        resetTela();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtfMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMarcaActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        resetTela();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        Pesquisa p = new Pesquisa();
        String[] opcoesBusca = {"ID", "Placa", "Marca", "Modelo", "Ano", "Status"};
        List<VeiculoModel> lista = p.pesquisaVeiculo(opcoesBusca);

        // Se a pesquisa retornar null o usuário pesquisou um valor vazio ou inválido (a mensagem especificando qual o valor inválido é exibida no método pesquisarVeiculo)
        if (lista == null) {
            resetTela();
        } // Se a pesquisa retornar uma lista com tamanho 0 o usuário não digitou nenhum valor inválido, mas não foi encontrado nenhum veículo no banco
        else if (lista.size() == 0) {
            JOptionPane.showMessageDialog(null, "Veículo não encontrado no banco de dados.");
            resetTela();
        } // Se a pesquisa retornar uma lista de tamanho 1, apenas um veículo foi encontrado na busca e os campos de texto são preenchidos
        else if (lista.size() == 1) {
            JOptionPane.showMessageDialog(this, "1 Veículo encontrado.\nExibindo o resultado nos campos de texto.");
            resetTela();
            VeiculoModel v = lista.get(0);

            jtfID.setText(Integer.toString(v.getId()));
            jtfPlaca.setText(v.getPlaca());
            jtfMarca.setText(v.getMarca());
            jtfModelo.setText(v.getModelo());
            jftfAno.setText(Integer.toString(v.getAno()));

            jbEditar.setEnabled(true);
            jbExcluir.setEnabled(true);
            jbLimpar.setEnabled(true);
        } // Se a pesquisa retornar uma lista de tamanho maior que 1, vários veículos foram encontrados e a tabela é preenchida com os resultados
        else {
            JOptionPane.showMessageDialog(this, lista.size() + " veículos encontrados.\nExibindo os resultados na tabela.");
            resetTela();
            DefaultTableModel model = (DefaultTableModel) TabelaVeiculos.getModel();
            model.setRowCount(0);

            for (VeiculoModel veiculoEncontrado : lista) {
                model.addRow(new Object[]{
                    veiculoEncontrado.getId(),
                    veiculoEncontrado.getPlaca(),
                    veiculoEncontrado.getMarca(),
                    veiculoEncontrado.getModelo(),
                    veiculoEncontrado.getAno(),
                    veiculoEncontrado.getStatus()
                });
            }
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void TabelaVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaVeiculosMouseClicked
        if (tabelaAtiva == true) {
            int linha = TabelaVeiculos.getSelectedRow();
            DefaultTableModel modelo = (DefaultTableModel) TabelaVeiculos.getModel();

            jtfID.setText((modelo.getValueAt(linha, 0)).toString());
            jtfPlaca.setText((modelo.getValueAt(linha, 1)).toString());
            jtfMarca.setText((modelo.getValueAt(linha, 2)).toString());
            jtfModelo.setText((modelo.getValueAt(linha, 3)).toString());
            jftfAno.setText((modelo.getValueAt(linha, 4)).toString());

            jbEditar.setEnabled(true);
            jbExcluir.setEnabled(true);
            jbLimpar.setEnabled(true);
            jbCancelar.setEnabled(false);
        }
    }//GEN-LAST:event_TabelaVeiculosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaVeiculos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JFormattedTextField jftfAno;
    private javax.swing.JLabel jlAno;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlPlaca;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfModelo;
    private javax.swing.JTextField jtfPlaca;
    // End of variables declaration//GEN-END:variables
}
